name: Organize LeetCode Solutions

on:
  push:
    branches:
      - master

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run organize script
        run: python organize.py